Repository five-star-school/eduWithMe-frontend, pull requests merged in 2024-08, with the labels that each got.

#130 [#129] ✨feat : 관리자 메인 페이지 api 연결 기능 구현
  src/App.js
  src/components/Manage/QuestionTable.jsx
  src/pages/ManageMainPage.jsx
  src/pages/QuestionUpdatePage.jsx
Labels: feat

#133 [#132] 🩹fix : 관리자 메인 페이지 수정
  src/pages/ManageMainPage.jsx
Labels: fix

#136 [#135] ✨ feat : 관리자 문제 상세 페이지 문제 조회 연결 및 삭제
  src/pages/ManageReadPage.jsx
Labels: feat

#137 [#134] ✨feat : 관리자 페이지 방 삭제 api 연결 기능 구현
  src/components/ManageMainHeaderNav.jsx
  src/pages/ManageMainPage.jsx
Labels: feat

#138 [#124] ✨feat : 마이페이지 roomName 테이블 추가 및 api 연동
  src/components/MyPage/MyComments.jsx
  src/components/MyPage/SolvedAnswers.jsx
  src/components/MyPage/UserInfo.jsx
  src/components/MyPage/WrongAnswers.jsx
  src/pages/MyPage.jsx
Labels: feat

#143 [#139] ✨ feat : 관리자 문제 수정 기능 API 연동
  src/App.js
  src/pages/ManageModifyPage.jsx
Labels: feat

#145 [#144] 🩹fix : 방 전체 조회 수정
  src/components/SpaceCard.jsx
Labels: fix

#150 [#148] ✨ feat : comment 수정 시간 표기 구현
  src/components/CommentSection.jsx
Labels: feat

#151 [#147] ✨ feat : 관리자 문제 생성 페이지 API 연동
  src/App.js
  src/components/Manage/QuestionSettings.jsx
  src/pages/ManageCreatePage.jsx
  src/pages/ManageMainPage.jsx
Labels: feat

#152 [#114] ✨ feat : 특정 사용자가 참여중인 방 목록 api 연동
  src/App.js
  src/components/Modal.jsx
  src/components/MyPage/MyRoom.jsx
  src/components/SpaceCard.jsx
  src/pages/MyPage.jsx
  src/pages/MyRoomPage.jsx
  src/styles/MyComments.module.css
  src/styles/SolvedAnswers.module.css
  src/util/AuthContext.js
  src/util/useAuth.js
Labels: feat

#157 [#155] ✨ feat : HomePage 플랫폼 소개 추가
  public/eduwithme.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App.js
  src/pages/HomePage.jsx
  src/styles/HomePage.module.css
Labels: feat

#164 [#156] ✨ feat : roommain, magemain 문제번호 새로 추가 부여 구현 완료
  src/components/ManageMainHeaderNav.jsx
  src/components/RoomMain.jsx
  src/pages/ManageMainPage.jsx
  src/pages/ManageReadPage.jsx
Labels: feat

#167 [#166] 🩹 fix : managemainpage 코드 중복 수정
  src/components/ManageMainHeaderNav.jsx
  src/pages/ManageMainPage.jsx
Labels: fix

#170 [#163] ✨ feat : 관리자 메인 페이지 출제일 조회 기능 구현
  src/pages/ManageMainPage.jsx
Labels: feat

#172 [#171] 🩹 fix : 관리자 문제 수정 기능 코드 수정
  src/components/ManageMainHeaderNav.jsx
Labels: fix

#174 [#173, #161] 🩹 fix : 백엔드 수정으로 인한 프론트 관리자 관련 수정, 난이도 정렬 추가 구현
  src/components/HeaderNavComponent.jsx
  src/components/ManageMainHeaderNav.jsx
  src/components/RoomLayout.jsx
  src/pages/ManageMainPage.jsx
  src/styles/ManageMainHeaderNav.module.css
Labels: fix

#176 [#175] ✨ feat : 관리자페이지에서 사이드바 상단 RoomName을 누르면 룸 조회화면으로 이동 구현
  src/components/SidebarComponent.jsx
Labels: feat

#180 [#178] 🩹 fix : 관리자 페이지 문제 조회, 생성, 수정 시 해당 방 표시 오류
  src/components/ManageMainHeaderNav.jsx
  src/pages/ManageCreatePage.jsx
  src/pages/ManageModifyPage.jsx
  src/pages/ManageReadPage.jsx
Labels: fix

#182 [#177] 🩹 fix : 문제 목록 css 통일
  src/App.js
  src/components/Login.jsx
  src/components/MainContentComponent.jsx
  src/components/MyPage/ChangePassword.jsx
  src/pages/ManageMainPage.jsx
  src/pages/MyPage.jsx
  src/styles/MainContentComponent.module.css
  src/styles/ManageMainPage.module.css
  src/styles/RoomMainPage.module.css
  src/styles/SidebarComponent.module.css
Labels: fix

#185 [#184] 🩹 fix : Room마다 독립적 QuestionId 부여 및 프론트 코드 수정
  src/components/MyPage/MyComments.jsx
  src/components/MyPage/SolvedAnswers.jsx
  src/components/MyPage/WrongAnswers.jsx
  src/components/RoomMain.jsx
  src/pages/ManageMainPage.jsx
  src/styles/ManageMainHeaderNav.module.css
Labels: fix

#187 [#179] 🩹 fix : 관리자 문제 조회 페이지 사이드바 수정
  src/components/ManageReadSidebar.jsx
  src/components/QuestionDetail.jsx
  src/pages/ManageReadPage.jsx
Labels: fix

#186 [#183] 🩹 fix : 관리자 페이지 컴포넌트 분리, CSS 수정
  src/components/Manage/AnswerOption.jsx
  src/components/Manage/ManageMainHeaderNav.jsx
  src/components/Manage/ManageReadSidebar.jsx
  src/components/Manage/QuestionDetail.jsx
  src/components/Manage/QuestionDetailModify.jsx
  src/components/Manage/QuestionDetailRead.jsx
  src/components/Manage/QuestionInfo.jsx
  src/components/MyPage/MyComments.jsx
  src/components/MyPage/SolvedAnswers.jsx
  src/index.css
  src/pages/ManageCreatePage.jsx
  src/pages/ManageMainPage.jsx
  src/pages/ManageModifyPage.jsx
  src/pages/ManageReadPage.jsx
  src/styles/ManageCreatePage.module.css
  src/styles/ManageModifyPage.module.css
  src/styles/ManageReadPage.module.css
  src/styles/QuestionDetail.module.css
Labels: fix

#189 [#188] 🩹 관리자 조회페이지도 이동 안되는 문제 수정
  src/pages/ManageReadPage.jsx
Labels: fix

#191 [#190] ✨ feat : 관리자 페이지 수정일 추가
  src/pages/ManageMainPage.jsx
  src/styles/ManageMainPage.module.css
Labels: feat

#193 [#192] ✨ feat : 룸 메인페이지 방 이름 검색창
  src/App.js
  src/components/SpaceCard.jsx
  src/styles/Header.module.css
  src/styles/HeaderNavComponent.module.css
  src/styles/ManageMainHeaderNav.module.css
  src/styles/MyPage.module.css
  src/styles/SpaceCard.module.css
Labels: feat

#195 [#194] 🩹fix : 모든 파일 백엔드 api path 수정
  src/components/ChatWidget.jsx
  src/components/CommentSection.jsx
  src/components/ForgotPassword.jsx
  src/components/Login.jsx
  src/components/Manage/ManageMainHeaderNav.jsx
  src/components/Modal.jsx
  src/components/MyPage/ChangePassword.jsx
  src/components/MyPage/MyRoom.jsx
  src/components/MyPage/UserInfo.jsx
  src/components/QuestionDetail.jsx
  src/components/RoomLayout.jsx
  src/components/RoomMain.jsx
  src/components/SidebarComponent.jsx
  src/components/Signup.jsx
  src/components/SpaceCard.jsx
  src/pages/ManageCreatePage.jsx
  src/pages/ManageMainPage.jsx
  src/pages/ManageModifyPage.jsx
  src/pages/ManageReadPage.jsx
  src/pages/MyPage.jsx
  src/pages/QuestionDetailPage.jsx
  src/util/AuthContext.js
Labels: fix

#197 [#196] 🩹 fix : 카카오 로그인 기능 수정
  src/App.js
  src/components/Header.jsx
  src/pages/KakaoRedirect.jsx
  src/pages/ManageReadPage.jsx
  src/util/AuthContext.js
  src/util/axiosConfig.js
Labels: fix

#199 [#198] ✨ feat : 인원수 api 연동
  src/components/ChatWidget.jsx
  src/components/Modal.jsx
  src/components/MyPage/UserInfo.jsx
  src/components/SpaceCard.jsx
  src/styles/SpaceCard.module.css
Labels: feat

#201 [#200] ✨ feat : 프로필 편집 이미지 업로드 api 연동
  src/components/MyPage/UserInfo.jsx
  src/pages/MyPage.jsx
Labels: feat

#204 [#203] ✨ feat : 회원가입 닉네임 중복 확인, 닉네임 변경 중복 확인, 회원탈퇴 기능 구현
  src/components/Header.jsx
  src/components/MyPage/UserInfo.jsx
  src/components/Signup.jsx
  src/pages/MyPage.jsx
  src/styles/MyPage.module.css
Labels: feat

#205 [#202] 💄 style : 전체적인 CSS 통일
  src/components/HeaderNavComponent.jsx
  src/components/MyPage/UserInfo.jsx
  src/components/QuestionDetail.jsx
  src/styles/Header.module.css
  src/styles/HeaderNavComponent.module.css
  src/styles/HomePage.module.css
  src/styles/ManageMainHeaderNav.module.css
  src/styles/ManageMainPage.module.css
  src/styles/MyComments.module.css
  src/styles/MyPage.module.css
  src/styles/QuestionDetail.module.css
  src/styles/RoomMainPage.module.css
  src/styles/SpaceCard.module.css
  src/styles/UserInfo.module.css
Labels: fix

#207 [#206] 🐛 bugfix : 파일 선택 창 버그 수정
  src/components/MyPage/UserInfo.jsx
Labels: bug

#209 [#208] ✨ feat : 마이룸 인원수 api 연동
  src/components/MyPage/MyRoom.jsx
Labels: feat

#213 [#212] 🩹 fix : 유저페이지 문제번호 최신순으로 수정 및 불필요한 콘솔로그 제거
  src/components/ChatWidget.jsx
  src/components/CommentSection.jsx
  src/components/HeaderNavComponent.jsx
  src/components/Login.jsx
  src/components/Manage/ManageMainHeaderNav.jsx
  src/components/Modal.jsx
  src/components/MyPage/ChangePassword.jsx
  src/components/QuestionDetail.jsx
  src/components/RoomLayout.jsx
  src/components/RoomMain.jsx
  src/components/SidebarComponent.jsx
  src/pages/ManageCreatePage.jsx
  src/pages/ManageMainPage.jsx
  src/pages/ManageModifyPage.jsx
  src/pages/ManageReadPage.jsx
  src/pages/MyPage.jsx
  src/util/AuthContext.js
Labels: fix

#217 [#216] 🩹 fix : 문제 생성 시 빈칸 있으면 문제 생성 불가능하게 수정
  src/pages/ManageCreatePage.jsx
Labels: fix

#218 [#215] 🩹 fix : public, private 버튼 클릭 hover 추가
  src/components/Modal.jsx
  src/styles/SpaceCard.module.css
Labels: fix

#220 [#219] ✨ feat : Gemini 추가 기능 구현
  package-lock.json
  package.json
  src/components/HeaderNavComponent.jsx
  src/styles/AIQuestionModal.module.css
  src/util/AIQuestionModal.js
Labels: feat

#225 fix : package.json CI 추가
  package.json
Labels: fix

#221 [#214] 🩹 fix : 비밀번호 정규식 수정
  src/components/MyPage/ChangePassword.jsx
Labels: fix

#224 [#223] 🩹 fix : 메인페이지 방 페이징 처리
  src/components/SpaceCard.jsx
  src/styles/SpaceCard.module.css
Labels: fix
